"""Render a small, offline workbench from the executed physical studies."""
import json
from html import escape
from pathlib import Path
from render_overview import page

ROOT = Path(__file__).resolve().parents[2]
DATA = ROOT / 'research/physics'


def select(id, label, values, selected):
    options = ''.join(f'<option value="{escape(str(value))}"'+
        (' selected' if value == selected else '')+f'>{escape(str(text))}</option>'
        for value, text in values)
    return f'<label for="{id}">{label}<select id="{id}">{options}</select></label>'


def exports(stem, files):
    return '<div class="download-links">'+''.join(
        f'<a href="/research/files/physics/{name}" download>{label} ↓</a>' for name,label in files)+f'<a href="/research/files/physics/{stem}.svg" download>Figure SVG ↓</a></div>'


def render():
    source = json.loads((DATA/'sources.json').read_text())
    source_cards = ''.join(f'<article class="source-card"><span class="evidence-label literature">{escape(s["authors"])} · {s["year"]}</span><h3><a href="{escape(s["url"])}">{escape(s["title"])}</a></h3><p>{escape(s["use"])}</p><details><summary>Reading depth & limit</summary><p>{escape(s["consulted"])}</p><p>{escape(s["limit"])}</p></details></article>' for s in source['sources'])
    crust_controls=select('crustDensity','Published south-density case',[(r,f'{r:,} kg/m³') for r in [2600,2700,2800,2900]],2700)+select('mantleDensity','Assumed mantle density',[(r,f'{r:,} kg/m³') for r in [3400,3500,3600]],3500)
    layers=select('basalThickness','Basal layer',[(r,f'{r} km') for r in [0,7,14]],14)+select('upperDensity','Upper grain density',[(r,f'{r:,} kg/m³') for r in [2600,2800,3000]],2800)+select('basalDensity','Basal density',[(r,f'{r:,} kg/m³') for r in [3200,3400,3600,3700]],3400)+select('porosity','Upper empty-pore fraction',[(r,f'{r*100:g}%') for r in [0,.05,.1,.15,.2]],.1)
    feedback_controls=select('lidThickness','Conductive lid thickness',[(r,f'{r} km') for r in [50,100,200]],100)+select('seedSpectrum','Initial power over degrees 1–20',[('equal_degree_power','Equal power per degree'),('equal_coefficient_power','Equal power per coefficient')],'equal_coefficient_power')+select('efolds','Degree-one amplitude e-folds',[(r,str(r)) for r in [0,1,3,5,10]],5)
    boundary_controls=select('longitude','MOLA strip center',[(r,f'{r}°E · ±1°') for r in [56,62,68,74]],62)+select('smoothing','Gaussian smoothing σ',[(r,f'{r} km') for r in [25,50,100]],50)+select('loadPeak','Assumed load change',[(r,'0 · no-load control' if r==0 else f'{r:+g} km') for r in [-1,-.5,0,.5,1]],1)+select('elasticThickness','Elastic thickness',[(r,f'{r} km') for r in [10,30,60]],30)+select('loadOffset','Load center relative to reference',[(r,f'{r:+g} km northward') for r in [-150,150]],150)+select('loadWidth','Gaussian load width σ',[(r,f'{r} km') for r in [100,200]],100)
    body=f'''<div class="route-context"><a href="/research/tests">← All research results</a><span>Three physical studies · one magnetic learning path</span></div>
<div class="physics-intro"><div><p class="eyebrow">ROCKS → HEMISPHERES → GEOLOGICAL MEMORY</p><h1>Put the mechanisms<br>to the test.</h1><p class="lead">Change an assumption. See what follows. Explore our calculations of crustal support, thermal amplification and deformation, then learn what a magnetic record can tell us.</p></div><div class="physics-scope"><span class="evidence-label">Executed · 27 September 2026</span><p>Real MOLA profiles and published crust models meet deliberately limited physical tests.</p><a href="/assets/reading/dichotomy_physics.html">Read the methods & findings →</a><small>These results do not yet select an origin of the dichotomy.</small></div></div>
<nav class="view-tabs" aria-label="Physical studies"><a href="?view=crust" data-view="crust" aria-current="page">01 · Composition</a><a href="?view=feedback" data-view="feedback">02 · Amplification</a><a href="?view=boundary" data-view="boundary">03 · Earlier boundary</a><a href="?view=paleomagnetism" data-view="paleomagnetism">Learn · Paleomagnetism</a></nav>
<p id="physicsStatus" role="status">Loading the saved calculations…</p>
<noscript><p class="notice">Interactive controls require JavaScript. All results, figures and methods are available in the <a href="/assets/reading/dichotomy_physics.html">physical studies report</a> and <a href="/assets/reading/paleomagnetism_foundations.html">magnetic learning guide</a>.</p></noscript>
<section class="physics-view" id="view-crust" aria-labelledby="crustTitle">
<div class="physics-question"><span class="evidence-label">Published maps + original accounting</span><h2 id="crustTitle">More crust, or lighter crust?</h2><p>Both can raise the surface. Across the four published density cases, the south–north thickness contrast changes from −2.35 to +23.15 km. The observed relief contrast stays at 3.18 km.</p></div>
<div class="map-controls">{crust_controls}</div>
<div class="physics-chart-grid"><div class="plot-panel"><div id="crustPlot" class="physics-plot" role="img" aria-label="Selected crustal support contributions compared with MOLA relief"></div></div><aside class="physics-readout"><p class="eyebrow">READ THIS RESULT</p><p id="crustSummary" aria-live="polite"></p><p class="physics-limit">These maps already use topography. The comparison is a support budget, not an independent fit or a best-density estimate.</p><a href="https://doi.org/10.1029/2022JE007298">Published crust models ↗</a></aside></div>
<details class="method-drawer"><summary>Explore a layered rock column</summary><p>Keep dense basal material in the mass budget. These 50 km columns are synthetic endmembers; no mineral assemblage or detachment timescale is calculated.</p><div class="map-controls">{layers}</div><p id="layerSummary" aria-live="polite"></p><p>Porosity is uniform in the upper layer, with empty pores. Support is above a shared compensation datum, not an absolute elevation. Mantle density here is fixed at 3,500 kg/m³.</p><p>A local seismic interpretation near InSight motivates the 14 km layer option; it is not a measured global layer. <a href="https://www.nature.com/articles/s41550-026-02907-5">Mackay-Champion et al. (2026) ↗</a></p></details>
<div class="physics-next"><b>What would move this forward?</b><p>Constrain density using rock composition, pressure, temperature and porosity with depth; retain the dense residue. A new fit needs joint gravity and seismic constraints.</p></div>
{exports('crust_support',[('crust_support.csv','Support CSV'),('layer_sensitivity.csv','Layer cases CSV'),('crust.json','All results JSON')])}
</section>
<section class="physics-view" id="view-feedback" aria-labelledby="feedbackTitle" hidden>
<div class="physics-question"><span class="evidence-label synthetic">Linear thermal benchmark</span><h2 id="feedbackTitle">Does a small lead become a whole hemisphere?</h2><p>Degree one is a hemispheric pattern. It grows fastest in this restricted shell model, but nearby spatial scales grow almost as fast. The initial distribution of power matters.</p></div>
<div class="map-controls">{feedback_controls}</div>
<div class="physics-two-plots"><div id="growthPlot" class="physics-plot" role="img" aria-label="Relative linear growth by spherical harmonic degree"></div><div id="powerPlot" class="physics-plot" role="img" aria-label="Power distribution after the selected amplification"></div></div>
<p class="physics-result" id="feedbackSummary" aria-live="polite"></p><p class="physics-limit">E-folds describe amplification, not elapsed geological time. Power shares depend on the selected initial spectrum and degree cutoff; they are not probabilities for Mars. Large growth extrapolates beyond the linear model.</p>
<details class="method-drawer"><summary>What is actually solved?</summary><p>A steady spherical conductive shell, with fixed surface-temperature perturbation and zero basal-flux perturbation. Relative thermal responses represent relative growth only if the other positive linear feedback factors are equal across degrees. There is no evolving mantle convection, melt depletion or saturation.</p><p>This tests a restricted part of an existing idea: <a href="https://doi.org/10.1029/2022JE007472">Bonnet Gibet et al. (2022)</a>. We independently implemented the solver; we do not claim a new mechanism.</p></details>
<div class="physics-next"><b>What would move this forward?</b><p>Conserve the finite melt and heat-producing-element inventory, add cooling and saturation, then test whether hemispheric structure survives several initial spectra and convective forcing.</p></div>
{exports('feedback_selection',[('feedback_modes.csv','Thermal modes CSV'),('feedback.json','Power histories JSON')])}
</section>
<section class="physics-view" id="view-boundary" aria-labelledby="boundaryTitle" hidden>
<div class="physics-question"><span class="evidence-label">Observed MOLA + assumed loads</span><h2 id="boundaryTitle">Which edge are we trying to restore?</h2><p>Undo an assumed load and compare the earlier surface it would imply. The picked boundary is only the steepest smoothed descent in 25–45°N. It can switch between different features.</p></div>
<div class="map-controls boundary-controls">{boundary_controls}</div>
<div id="boundaryPlot" class="physics-plot wide" role="img" aria-label="Observed MOLA profile, conditional earlier relief and their steepest-descent proxies"></div>
<p class="physics-result" id="boundarySummary" aria-live="polite"></p><p class="physics-limit" id="boundaryCaution"></p>
<details class="method-drawer"><summary>Why this is not yet an ancient boundary map</summary><p>Every assumed-load case reproduces the present profile exactly by construction. The family has 48 load cases and a no-load control per strip. Neither loading history nor age is measured here. Relief alone cannot select a unique history.</p><p>Positive thickness adds a surface load; negative thickness removes it. The model is an elastic plate with a free surface, not a fault-slip or frictional-viscous detachment restoration. The strips are meridional, not necessarily normal to the geological boundary. Numerical resolution is 14.8 km north–south.</p><p>Sources: <a href="https://pds-geosciences.wustl.edu/missions/mgs/megdr.html">NASA MOLA</a>, <a href="https://repository.si.edu/bitstreams/37c12736-89e7-4c26-8fb8-9200782c2237/download">Watters (2003)</a>, and the regional motivation in <a href="https://doi.org/10.1016/j.epsl.2025.119645">Carboni et al. (2025)</a>.</p></details>
<div class="physics-next"><b>Try the ambiguous profile.</b><p>Select 56°E, keep the no-load control, and change smoothing from 50 to 100 km. The proxy jumps about 830 km between features. That is a failed feature match, not a tectonic displacement.</p><b>What would move this forward?</b><p>Track the same dated scarps and deposits across neighboring strips, constrain load history and compare elastic, fault-slip, erosional and viscous explanations.</p></div>
{exports('boundary_restoration',[('mola_transects.csv','Observed strips CSV'),('boundary_scenarios.csv','Scenario shifts CSV'),('boundary.json','All profiles JSON')])}
</section>
<section class="physics-view" id="view-paleomagnetism" aria-labelledby="paleoTitle" hidden>
<div class="physics-question"><span class="evidence-label laboratory">Learn through a known-input control</span><h2 id="paleoTitle">A perfect line can give the wrong ancient field.</h2><p>Natural and laboratory remanence must respond comparably before a slope can become a field estimate. Here, every line is exact. Only the assumed recording efficiency changes.</p></div>
<div class="map-controls">{select('recordingEfficiency','Natural / laboratory recording efficiency',[(r,f'{r:g} ×') for r in [.5,1,2]],1)}<span class="physics-fixed">Known input: 25 µT · Laboratory field: 50 µT</span></div>
<div class="physics-chart-grid"><div id="araiPlot" class="physics-plot" role="img" aria-label="Synthetic Arai plot of natural remanence remaining versus laboratory remanence gained"></div><aside class="physics-readout"><p class="eyebrow">CHECK THE CONVERSION</p><p id="paleoSummary" aria-live="polite"></p><p class="physics-limit">An educational counterexample, not a measured meteorite or a calibration model for a specific mineral.</p><a href="/assets/reading/paleomagnetism_foundations.html">Follow the six-step learning guide →</a></aside></div>
<div class="physics-lessons"><article><b>01 · Identify the recorder</b><p>Moment, magnetization and field are different quantities. Check units, grain properties and acquisition process.</p></article><article><b>02 · Test the component</b><p>A small angular scatter describes a fit. Our contaminated control also produces straight components.</p><a href="/research/experiments?view=laboratory">Inspect the real control →</a></article><article><b>03 · Justify the inference</b><p>Acquisition age, alteration, anisotropy, cooling and orientation need their own evidence before a planetary claim.</p></article></div>
<details class="method-drawer"><summary>Exercise: would more points fix this?</summary><p>More exact points reduce fitting uncertainty but do not fix the unknown efficiency ratio. In this example, apparent field = efficiency ratio × true field. A specific laboratory protocol needs independent controls; a straight line alone cannot validate that conversion.</p><p>Read <a href="https://earthref.org/MagIC/books/Tauxe/Essentials/">Essentials of Paleomagnetism</a>, <a href="https://doi.org/10.1002/2013GC005135">Paterson et al. (2014)</a> and <a href="https://doi.org/10.3389/feart.2014.00024">Biggin & Paterson (2014)</a>. Our guide records which sections were consulted and connects them to the datasets we actually have.</p></details>
{exports('paleointensity_control',[('arai_counterexample.csv','Synthetic points CSV'),('paleomagnetism.json','Cases JSON')])}
</section>
<section class="physics-trace"><h2>Follow every result back to its assumptions.</h2><div class="download-links"><a href="/assets/reading/dichotomy_physics.html">Methods & findings →</a><a href="/assets/reading/paleomagnetism_foundations.html">Paleomagnetism guide →</a><a href="/research/files/physics/protocol.json" download>Protocol ↓</a><a href="/research/files/physics/manifest.json" download>Run manifest ↓</a><a href="/research/files/physics/input_provenance.json" download>Input provenance ↓</a><a href="/research/files/physics/sources.json" download>Reading ledger ↓</a></div><details class="reading-drawer"><summary>Primary sources · reading depth and limits for all 14 references</summary><div class="source-list">{source_cards}</div></details><p class="physics-limit">Independent project code and figures. Existing MOLA and CC BY 4.0 crust/boundary extracts retain source attribution. No external code, article figures or private internship material is used.</p></section>'''
    scripts='<link rel="stylesheet" href="/assets/physics.css?v=1"><script defer src="/assets/plotly.min.js"></script><script defer src="/assets/physics.js?v=1"></script>'
    (ROOT/'web/physics.html').write_text(page('Physical studies','/research/tests',body,scripts))


if __name__ == '__main__':
    render()
