'use strict';
const $=id=>document.getElementById(id);
const make=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
const link=(label,url)=>{const e=make('a',label);e.href=url;return e;};
const num=(v,n=1)=>typeof v==='number'?v.toLocaleString('en-US',{maximumFractionDigits:n,minimumFractionDigits:n}):v??'Not reported';
const get=async name=>{const r=await fetch('/research/files/data/'+name+'.json');if(!r.ok)throw Error('Could not load '+name+'. Please reload or use the source downloads.');return r.json();};
const config={responsive:true,displaylogo:false,scrollZoom:false,modeBarButtonsToRemove:['sendDataToCloud','select2d','lasso2d','autoScale2d']};
const layout={paper_bgcolor:'transparent',plot_bgcolor:'#1b1a19',font:{family:'Arial, sans-serif',color:'#bdb5ad',size:11},margin:{l:57,r:32,t:25,b:52},xaxis:{gridcolor:'#38312b',zeroline:false},yaxis:{gridcolor:'#38312b',zeroline:false},legend:{orientation:'h',y:1.15}};
let atlas,met,depths,thermal,results,lab,manifest;
const sourceUse={magnetic_field:'Evaluated at 150 and 400 km',magnetic_depth:'Parsed with uncertainty and fit-quality flags',crustal_models:'Four published grids analyzed; full ensemble archived',ejection_ages:'Original age table parsed',ejection_models:'Downloaded; morphological analysis pending',thermal_profiles:'Present-day compatibility diagnostics completed',mola:'Mapped as 2° block averages',lagain2022:'Candidate location and isotope table retained',herd2024:'Samples, groups and crater candidates parsed',geology:'44 units mapped; candidate points classified',rock_magnetism:'1,073 measurements parsed; contamination context retained'};
async function init(){
 try{
  if($('testStatus')){[results,thermal]=await Promise.all([get('results'),get('thermal')]);renderTests();return;}
  const view=new URLSearchParams(location.search).get('view')||'map';
  for(const a of document.querySelectorAll('[data-view]'))if(a.dataset.view===view)a.setAttribute('aria-current','page');
  if(view==='sources'){manifest=await get('manifest');renderSources();$('sourcesView').hidden=false;}
  else if(view==='laboratory'){lab=await get('laboratory');$('laboratoryView').hidden=false;renderLab();}
  else if(view==='meteorites'){met=await get('meteorites');renderSamples();renderGroups();$('sampleSearch').addEventListener('input',renderSamples);$('meteoriteView').hidden=false;}
  else{[atlas,met,depths]=await Promise.all([get('atlas'),get('meteorites'),get('depths')]);$('mapView').hidden=false;setupMap();}
  $('dataStatus').textContent='';$('dataStatus').hidden=true;
 }catch(e){const status=$('testStatus')||$('dataStatus');status.textContent=e.message;status.setAttribute('role','alert');}
}
function setupMap(){
 for(const c of met.craters){const o=make('option',c.name==='Unnamed'?`Unnamed · ${c.id}`:c.name);o.value=c.id;$('candidateSite').append(o);}
 const p=new URLSearchParams(location.search),allowed=['topography','magnetic','crust','geology','depth'];
 $('candidateSite').value=met.craters.some(c=>c.id===p.get('site'))?p.get('site'):'lagain-karratha';
 if(['150','400'].includes(p.get('altitude')))$('magHeight').value=p.get('altitude');
 if(['2600','2700','2800','2900'].includes(p.get('density')))$('crustDensity').value=p.get('density');
 if(allowed.includes(p.get('layer')))$('mapLayer').value=p.get('layer');
 for(const id of ['mapLayer','magHeight','crustDensity','candidateSite'])$(id).addEventListener('change',()=>{const u=new URL(location.href);u.searchParams.set('layer',$('mapLayer').value);u.searchParams.set('site',$('candidateSite').value);u.searchParams.set('altitude',$('magHeight').value);u.searchParams.set('density',$('crustDensity').value);history.replaceState(null,'',u);drawMap();});
 drawMap();
 $('observationMap').on('plotly_click',e=>{const p=e.points[0];if(typeof p.customdata==='string'&&met.craters.some(c=>c.id===p.customdata)){$('candidateSite').value=p.customdata;$('candidateSite').dispatchEvent(new Event('change'));}else if(p.data.type==='heatmap'){cellDetail(p);}});
}
const magneticColors=[[0,'#000004'],[.125,'#1c1044'],[.25,'#4f127b'],[.375,'#812581'],[.5,'#b5367a'],[.625,'#e55964'],[.75,'#fb8761'],[.875,'#fec287'],[1,'#fcfdbf']];
const topoColors=[[0,'#41465b'],[.23,'#8d929a'],[.34,'#c8b8a5'],[.45,'#c19170'],[.65,'#9a5133'],[.85,'#ce9264'],[1,'#efe0c5']];
function drawMap(){
 const kind=$('mapLayer').value,h=$('magHeight').value,density=$('crustDensity').value,c=met.craters.find(c=>c.id===$('candidateSite').value);
 $('heightControl').hidden=kind!=='magnetic';$('densityControl').hidden=kind!=='crust';
 let z=atlas.topography_km,colors=topoColors,title='km',min=-8,max=22,caption='MOLA elevation relative to the areoid. Surface elevation is not crustal thickness.',ticks;
 if(kind==='magnetic'){z=atlas.magnetic_nT[h].map(row=>row.map(v=>Math.log10(Math.max(v,.01))));colors=magneticColors;title='nT';min=0;max=3;ticks={tickvals:[0,1,2,3],ticktext:['1','10','100','1,000']};caption=`Langlais et al. (2019): modeled crustal |B| at ${h} km above the 3,393.5 km reference sphere; degree 134. This is not a meteorite paleointensity. Fixed color scale at both altitudes.`;}
 if(kind==='crust'){z=atlas.crust_km[density];colors='YlOrBr';title='km';min=0;max=120;caption=`Wieczorek et al. (2022), Khan2022 interior, 39 km at InSight; north density 2,900 and south ${num(+density,0)} kg/m³. Four selected models illustrate assumptions; they are not a confidence interval.`;}
 if(kind==='geology'){z=atlas.geology.grid.map(row=>row.map(v=>v<0?null:v));colors=Array.from({length:44},(_,i)=>[i/43,`hsl(${[15,28,38,280,330,225][i%6]},${20+i%3*13}%,${27+i%5*10}%)`]);title='Unit';min=-.5;max=43.5;caption='Tanaka et al. (2014), USGS SIM 3292, 1:20 million. Hover for a unit; click a cell for its interpretation. This is surface geology, not deep source lithology.';}
 if(kind==='depth')caption='Gong et al. (2021): equivalent source depth from overlapping 20° windows. Colored points have nonnegative fits and available bounds; grey crosses are excluded. This is not magnetic-layer thickness or a Curie depth.';
 let heat={type:'heatmap',x:atlas.longitude,y:atlas.latitude,z,colorscale:colors,zmin:min,zmax:max,colorbar:{title:{text:title},thickness:10,len:.7,...ticks},hovertemplate:kind==='geology'?'%{x}°E, %{y}°N<br>%{text}<extra></extra>':kind==='magnetic'?'%{x}°E, %{y}°N<br>|B| %{customdata:.2f} nT<extra></extra>':'%{x}°E, %{y}°N<br>%{z:.2f} '+title+'<extra></extra>',showscale:kind!=='geology'&&kind!=='depth'};
 if(kind==='magnetic')heat.customdata=atlas.magnetic_nT[h];
 if(kind==='geology')heat.text=atlas.geology.grid.map(row=>row.map(v=>v<0?'Unassigned or ambiguous':atlas.geology.units[v].Unit+' · '+atlas.geology.units[v].UnitDesc));
 if(kind==='depth'){heat.opacity=.18;heat.z=atlas.topography_km;heat.colorscale=topoColors;heat.zmin=-8;heat.zmax=22;}
 const traces=[heat];
 const bx=[],by=[];let prev=null;for(const [x,y] of atlas.boundary){if(prev!==null&&Math.abs(x-prev)>180){bx.push(null);by.push(null);}bx.push(x);by.push(y);prev=x;}
 traces.push({type:'scatter',x:bx,y:by,mode:'lines',line:{color:'#e8ddcb',width:1.3,dash:'dot'},hoverinfo:'skip',showlegend:false});
 if(kind==='depth')for(const valid of [true,false]){const d=depths.filter(d=>d.usable===valid);traces.push({type:'scatter',x:d.map(d=>d.lon),y:d.map(d=>d.lat),mode:'markers',marker:{size:valid?7:5,symbol:valid?'circle':'x',color:valid?d.map(d=>d.depth_km):'#b8b4b0',colorscale:magneticColors,cmin:0,cmax:100,showscale:valid,colorbar:{title:{text:'km'},thickness:10,len:.7}},text:d.map(d=>valid?`${num(d.depth_km)} km; interval ${num(d.lower_km)} to ${num(d.upper_km)} km`:`Excluded: fit ${num(d.depth_km)} km; ${d.interval_available?'interval available':'no interval'}`),hovertemplate:'%{text}<extra></extra>',showlegend:false});}
 traces.push({type:'scatter',x:met.craters.map(c=>c.lon),y:met.craters.map(c=>c.lat),customdata:met.craters.map(c=>c.id),text:met.craters.map(c=>c.name==='Unnamed'?c.id:c.name),mode:'markers',marker:{symbol:'x',size:7,color:'#f7eddf',line:{width:1}},hovertemplate:'%{text}<br>Candidate source<extra></extra>',showlegend:false});
 traces.push({type:'scatter',x:[c.lon],y:[c.lat],customdata:[c.id],mode:'markers',marker:{symbol:'circle-open',size:20,color:'#ffdb83',line:{width:2}},hovertemplate:c.name+'<extra></extra>',showlegend:false});
 Plotly.react('observationMap',traces,{...layout,margin:{l:49,r:kind==='geology'?15:60,t:20,b:48},xaxis:{...layout.xaxis,title:{text:'East longitude (°)'},range:[0,360],dtick:60},yaxis:{...layout.yaxis,title:{text:'Latitude (°)'},range:[-90,90],dtick:30},uirevision:'mars-map'},config);
 $('mapCaption').textContent=caption;siteDetail(c);
}
function siteDetail(c){
 const root=$('siteDetails');root.replaceChildren(make('span','PROPOSED SOURCE','tag'),make('h2',c.name==='Unnamed'?c.id:c.name),make('p',`${num(Math.abs(c.lat))}°${c.lat<0?'S':'N'} · ${num(c.lon)}°E · ${num(c.diameter_km)} km diameter`));
 const dl=make('dl');for(const [k,v] of [['Linked ejection groups',c.groups.length?c.groups.join(', '):'No preferred link in this compilation'],['Crustal model field at 150 km',num(c.field_150_nT)+' nT'],['At 400 km',num(c.field_400_nT)+' nT'],['Crater-center surface unit',c.geologic_units_at_point?.map(u=>u.Unit).join(', ')||'Unassigned / boundary'],['Surrounding unit reported in source',c.reported_unit||'See source study']])dl.append(make('dt',k),make('dd',v));root.append(dl,make('p',c.status));
 for(const u of c.geologic_units_at_point||[])root.append(make('p',u.UnitDesc));
 root.append(link('Published source ↗',c.source_url),make('p','The orbital field describes the surroundings today. It does not measure the ancient field recorded by a meteorite.'));
 if(c.coordinate_note){const d=make('details');d.append(make('summary','Coordinate correction'),make('p',c.coordinate_note));root.append(d);}
 if(c.excavation?.length){const d=make('details');d.append(make('summary','Modeled excavation depths'));for(const r of c.excavation)d.append(make('p',r.sample+': '+r.maximum_depth_as_reported));root.append(d);}
}
function cellDetail(p){const root=$('siteDetails'),i=atlas.latitude.indexOf(p.y),j=atlas.longitude.indexOf(p.x);if(i<0||j<0)return;const unit=atlas.geology.grid[i][j];root.replaceChildren(make('span','DISPLAY CELL','tag'),make('h2',`${p.x}°E, ${p.y}°N`),make('p','A 2° display cell. Use the candidate menu to return to a proposed meteorite source.'));for(const [name,value] of [['Elevation',num(atlas.topography_km[i][j])+' km above areoid'],['Modeled |B| at 150 km',num(atlas.magnetic_nT['150'][i][j])+' nT']])root.append(make('h3',name),make('p',value));if(unit>=0){const u=atlas.geology.units[unit];root.append(make('h3',u.Unit+' · '+u.UnitDesc),make('p',u.Interpretation));}}
function renderSamples(){const q=($('sampleSearch').value||'').toLowerCase(),rows=met.samples.filter(s=>[s.name,s.type,s.ejection_group].join(' ').toLowerCase().includes(q));$('sampleCount').textContent=`${rows.length} of ${met.samples.length} sample records · Herd et al. (2024), Data S1`;$('sampleRows').replaceChildren(...rows.map(s=>{const r=make('tr');for(const v of [s.name,s.type,s.ejection_group,s.ejection_Ma==null?'Not reported':num(s.ejection_Ma,2)+(s.ejection_sigma_Ma!=null?' ± '+num(s.ejection_sigma_Ma,2)+' (1σ)':''),s.crystallization_Ma==null?'Not reported':num(s.crystallization_Ma,0)+(s.crystallization_2sigma_Ma!=null?' ± '+num(s.crystallization_2sigma_Ma,0)+' (2σ)':'')])r.append(make('td',v));return r;}));}
function renderGroups(){for(const g of met.groups){const d=make('details');d.append(make('summary',g.group+' · '+g.petrology),make('p',g.main_samples),make('p',`Exposure: ${g.exposure_Ma_as_reported} Ma. Crystallization: ${g.crystallization_Ma_as_reported}.`),make('p',`Preferred candidate in this study: ${g.preferred_candidate||'not selected'}. Province: ${g.province}.`));const c=met.craters.find(c=>c.name===g.preferred_candidate||(g.group==='group 5-2'&&c.name==='Karratha'));if(c)d.append(link('Inspect candidate on the map →','/research/data?site='+encodeURIComponent(c.id)));d.append(make('h3','Alternatives & conditions'));const ul=make('ul');g.alternatives.forEach(a=>ul.append(make('li',a)));d.append(ul);$('ejectionGroups').append(d);}}
function renderSources(){for(const s of manifest){const c=make('article',undefined,'source-card');c.append(make('span',s.status==='downloaded'?'DOWNLOADED':'PARTIAL / UNAVAILABLE','tag'),make('h3',s.title),make('p',sourceUse[s.id]||'Downloaded; additional model analysis pending.'),make('p',s.limitation),link('Original archive ↗',s.landing_url),make('p','License: '+s.license));const d=make('details');d.append(make('summary',`${s.files?.length||0} products · files & checksums`));const ul=make('ul');for(const f of s.files||[]){const li=make('li');li.append(link(f.name,f.url),make('p',f.status+(f.bytes?' · '+num(f.bytes/1e6,2)+' MB':'')+(f.error?' · '+f.error:'')));if(f.sha256)li.append(make('code','SHA256 '+f.sha256));ul.append(li);}d.append(ul);c.append(d);$('sourceCards').append(c);}}
function renderLab(){for(const s of lab.specimens){const o=make('option',s.specimen);o.value=s.specimen;$('labSpecimen').append(o);}$('labSpecimen').addEventListener('change',drawLab);drawLab();}
function drawLab(){const rows=lab.measurements.filter(m=>m.specimen===$('labSpecimen').value);const x=rows.map((_,i)=>i+1),mom=rows.map(m=>+m.magn_moment);Plotly.react('labPlot',[{type:'scatter',mode:'lines+markers',x,y:mom,marker:{size:4,color:'#df9470'},line:{width:1},text:rows.map(m=>`${m.method_codes}<br>Archived AF treatment: ${num(+m.treat_ac_field*1000,2)} mT<br>Quality: ${m.quality}`),hovertemplate:'Step %{x}<br>Moment %{y:.3e} A m²<br>%{text}<extra></extra>'}],{...layout,xaxis:{...layout.xaxis,title:{text:'Measurement order (as archived)'}},yaxis:{...layout.yaxis,title:{text:'Remanent moment (A m²)'},type:'log'}},config);$('labCaption').textContent=`${rows.length} archived measurements for ${$('labSpecimen').value}. Shown by acquisition order: treatment amplitudes contain a discontinuity in some series. Values and method codes are preserved, not silently corrected or used to fit a paleofield. Hover for the archived treatment amplitude.`;}
function testCard(number,title,result,meaning,limit){const c=make('article',undefined,'test-card');c.append(make('span',number+' / COMPLETED DIAGNOSTIC','tag'),make('h2',title),make('div',result,'result-line'),make('p',meaning,'test-result'),make('p',limit));const d=make('details');d.append(make('summary','Method, sensitivity & evidence'));c.append(d);$('testCards').append(c);return d;}
function tableIn(parent,headers,rows){const wrap=make('div',undefined,'table-scroll'),t=make('table'),h=make('tr');headers.forEach(x=>h.append(make('th',x)));const head=make('thead');head.append(h);t.append(head);const b=make('tbody');rows.forEach(row=>{const r=make('tr');row.forEach(x=>r.append(make('td',x)));b.append(r);});t.append(b);wrap.append(t);parent.append(wrap);}
function drawThermal(){const traces=['North','South'].map((h,i)=>({type:'scatter',mode:'lines',x:thermal[h].BestModel.temperature_k,y:thermal[h].BestModel.depth_km,name:h,line:{color:i?'#df9470':'#829ab4'}}));Plotly.react('thermalProfiles',traces,{...layout,xaxis:{...layout.xaxis,title:{text:'Temperature (K)'},range:[200,1300]},yaxis:{...layout.yaxis,title:{text:'Depth below local surface (km)'},range:[180,0]},shapes:[598.15,853.15,943.15].map(x=>({type:'line',x0:x,x1:x,y0:0,y1:180,line:{color:'#777',width:1,dash:'dot'}}))},config);}
function renderTests(){
 $('testStatus').textContent=`Run completed ${new Date(results.generated_at).toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'})} · Saved results from ${results.counts.downloaded_products} downloaded products. No origin mechanism selected.`;
 const m=results.boundary_magnetic_contrast,a=results.depth_quality,c=results.crust_density_sensitivity;
 let d=testCard('01','Does the magnetic contrast survive a fair comparison?',`${num(m[0].south_north_ratio)}× at 150 km · ${num(m[1].south_north_ratio)}× at 400 km`,'The mean modeled field is stronger south of the published dichotomy boundary at both comparison altitudes.','This ratio is descriptive. Geometry, age, cancellation and preservation can all affect it; it does not select a dynamo history.');
 d.append(make('p','Full degree-134 Langlais field, 2° cell centers, cosine-latitude area weights; north/south of the Andrews-Hanna boundary supplied with the crust archive. Same height and model in both regions.'));tableIn(d,['Altitude','North mean','South mean','Ratio'],m.map(x=>[x.altitude_km+' km',num(x.north_mean_nT)+' nT',num(x.south_mean_nT)+' nT',num(x.south_north_ratio)]));tableIn(d,['Latitude-only check','Altitude','South / north'],results.magnetic_contrast.map(x=>[`|latitude| > ${x.exclude_equatorial_degrees}°`,x.altitude_km+' km',num(x.south_north_ratio)]));d.append(link('Explore the magnetic map →','/research/data?layer=magnetic'));
 d=testCard('02','Which source-depth estimates can we use?',`${a.usable} of ${a.windows} windows pass the basic quality gate`,`${a.unavailable_intervals} windows lack published bounds; ${a.negative_best_fits} have a negative best-fit depth. These categories overlap.`,'Windows overlap geographically. They are not independent measurements, and an equivalent source depth is not the bottom of the magnetized crust.');d.append(make('p','A usable estimate has a nonnegative best-fit depth and finite bounds bracketing that value. Published -1e100 sentinels are missing bounds, not extreme physical depths. Rejected estimates remain in the downloadable table.'));d.append(link('Inspect all depth fits →','/research/data?layer=depth'));
 const pyrr=results.thermal_gate.find(x=>x.hemisphere==='South'&&x.carrier==='Pyrrhotite');
 d=testCard('03','Can these depths be cool enough today?',`${pyrr.usable_windows-pyrr.below_ordering_temperature} of ${pyrr.usable_windows} southern best fits exceed the pyrrhotite threshold`,`${pyrr.whole_physical_interval_above} remain entirely above that threshold over their depth interval, under the chosen endpoint profile. All southern best fits pass the magnetite check.`,'Passing this check cannot show that a rock acquired or retained its remanence through past heating. Grain size, time, chemistry and different mineral compositions are not modeled.');
 tableIn(d,['Region / carrier','Best fit below T','Whole depth interval below T','Model threshold depth'],results.thermal_gate.map(x=>[x.hemisphere+' / '+x.carrier,x.below_ordering_temperature+' / '+x.usable_windows,x.whole_physical_interval_below+' / '+x.usable_windows,num(x.best_model_crossing_km)+' km']));d.append(make('p','Thresholds used: pyrrhotite 598.15 K, magnetite 853.15 K, hematite 943.15 K (Néel temperature for hematite). Temperatures are interpolated below each profile’s own surface; no extrapolation. Curie / Néel temperatures are not blocking temperatures. Profiles are assigned using each window center’s side of the published dichotomy boundary. Windows can cross that boundary. The whole-interval column tests its nonnegative portion; no confidence probability is assigned.'));if(results.south_min_max_identical)d.append(make('p','Source audit: the published southern “Min” and “Max” temperature files are identical. We do not present them as a validated uncertainty envelope.'));const plot=make('div',undefined,'science-plot');plot.id='thermalProfiles';d.append(plot);d.addEventListener('toggle',event=>{if(event.currentTarget.open)drawThermal();});d.append(link('Thermal model source ↗','https://doi.org/10.1002/2017JE005431'));
 d=testCard('04','How much does crustal density change the picture?',`${num(c[0].south_minus_north_km)} to ${num(c[c.length-1].south_minus_north_km)} km south–north difference`,'Changing assumed crustal density changes the thickness contrast, even with the same 39 km InSight anchor and interior model.','Four published examples are a sensitivity comparison, not the full ensemble or a probability distribution. Thickness and density must be considered together.');tableIn(d,['Southern density','North thickness','South thickness','Difference'],c.map(x=>[num(x.south_density_kg_m3,0)+' kg/m³',num(x.north_mean_km)+' km',num(x.south_mean_km)+' km',num(x.south_minus_north_km)+' km']));d.append(make('p','North density fixed at 2,900 kg/m³. Khan2022 interior model, 39 km local InSight thickness. Area-weighted means separated by the archive’s dichotomy boundary; Tharsis included.'));d.append(link('Compare crustal models →','/research/data?layer=crust'));
 d=testCard('05','Can we connect a meteorite’s magnetism to a region?',`${results.counts.candidate_craters} candidate craters · ${results.counts.laboratory_measurements.toLocaleString('en-US')} laboratory measurements`,'Candidate source associations can be explored alongside surface geology and the orbital field. The NWA 7034 paired-stone laboratory data also demonstrate why contamination screening matters.','This is a provenance and quality audit, not a regional paleointensity test. Launch sites are uncertain; hand-magnet-contaminated remanence cannot constrain an ancient Martian field.');d.append(make('p',`${results.counts.meteorites} sample records, ${results.counts.ejection_groups} ejection-group entries, ${results.counts.laboratory_specimens} laboratory specimens. These counts describe different sampling levels, not independent sites.`),link('Open laboratory measurements →','/research/data?view=laboratory'));
}
init();
